language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install flake8

script:
  - flake8 .

deploy:
  - provider: script
    script: git remote add flynn "https://user:$KEY@kjwon15.tk/postg" && git -c http.sslVerify=false push flynn "$TRAVIS_BRANCH":master
